version: '3.7'

services:
    php:
        build:
            context: ./
            dockerfile: dev.Dockerfile
            args:
                - HOST_UID=${HOST_UID}
        depends_on:
            - db
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        entrypoint: ./config/docker/dev/docker-entrypoint.sh
        environment:
            - COMPOSER_HOME=/var/www/html/var/composer
            - PHP_IDE_CONFIG
            - APP_ENV
            - SYMFONY_PHPUNIT_VERSION
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        ports:
            - "${EXTERNAL_HTTP_PORT-80}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    db:
        image: postgres:12.2
        ports:
            - "${EXTERNAL_DB_PORT-5432}:5432"
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_NAME-dev}
            - POSTGRES_USER=${DB_USER-dev}
            - POSTGRES_PASSWORD=${DB_PASSWORD-dev}
    mailhog:
        image: mailhog/mailhog
        ports:
        - "${EXTERNAL_SMTP_PORT-8025}:1025"
        - "${EXTERNAL_SMTP_WEB_PORT-8025}:8025"

volumes:
    db:
