version: '3.7'

services:
    php:
        build:
            context: ./config/docker/dev
            args:
                - HOST_UID=${HOST_UID}
        depends_on:
            - db
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        entrypoint: ./config/docker/dev/docker-entrypoint.sh
        environment:
            - COMPOSER_HOME=/var/www/html/var/composer
            - PHP_IDE_CONFIG
            - APP_ENV
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        ports:
            - "${EXTERNAL_HTTP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    db:
        image: postgres:10.6
        ports:
            - "${EXTERNAL_DB_PORT}:5432"
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - DB_NAME
            - DB_USER
            - DB_PASSWORD
    mailhog:
        image: mailhog/mailhog
        ports:
        - "1025:1025"
        - "8025:8025"

volumes:
    db:
